// AprendiendoAngular/src/app/components/formulario/formulario.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-formulario',
    templateUrl: './formulario.component.html',
    styleUrls: ['./formulario.component.css']
})
export class FormularioComponent implements OnInit {
    public user: any;
    public campo: string;
    public keyPressed: string;


    constructor() {
        this.user = {
            name: '',
            lastname: '',
            bio: '',
            genre: ''
        };
    }

    ngOnInit(): void {
    }

    onSubmit(): void {
        console.log(this.user);
    }

    onClick(): void {
        alert('Haz dado click');
    }

    onBlur(): void {
        alert('haz salido del input');
    }

    onKeyPress(evt) {
        this.keyPressed = `Haz presionado: ${evt.key}`;


    }

}

<app-slider [name]="'Formulario'" [size]="'small'"></app-slider>

<div class="center">
    <section class="content">

        <h2 class="subheader">Formulario</h2>

        <form class="mid-form" (ngSubmit)="onSubmit()" #userForm="ngForm">
            <div class="form-group">
                <label for="name">Nombre: </label>
                <input type="text" name="name" #name="ngModel" [(ngModel)]="user.name" required pattern="[a-zA-Z]+">
                <small *ngIf="name.invalid && name.touched">El nombre no es valido</small>
            </div>
            <div class="form-group">
                <label for="lastname">Apellido: </label>
                <input type="text" name="lastname" #lastname="ngModel" [(ngModel)]="user.lastname" required>
                <small *ngIf="lastname.invalid && lastname.touched">El apellido no es valido</small>
            </div>
            <div class="form-group radio">
                <label for="name">Biografia: </label>
                <textarea name="bio" cols="30" rows="10" #bio="ngModel" [(ngModel)]="user.bio" required></textarea>
                <small *ngIf="bio.invalid && bio.touched">La bio no es valida</small>
            </div>
            <div class="form-group radio">
                <input type="radio" name="genre" value="hombre" #genre="ngModel" [(ngModel)]="user.genre" required> Hombre
                <input type="radio" name="genre" value="mujer" #genre="ngModel" [(ngModel)]="user.genre"> Mujer
                <input type="radio" name="genre" value="otro" #genre="ngModel" [(ngModel)]="user.genre"> Otro
                <small *ngIf="genre.invalid && genre.touched">El genero no es valido</small>
            </div>
            <div class="clearfix"></div>

            <input type="submit" value="Enviar" class="btn btn-success" [disabled]="userForm.invalid">
        </form>

        <h2 class="sunheader">Eventos</h2>
        <button (click)="onClick()">Click</button>

        <p>blur</p>
        <input type="text" [(ngModel)]="campo" (blur)="onBlur()">
        <p> {{campo}} </p>

        <p>keypress</p>
        <input type="text" [(ngModel)]="campo" (keypress)="
        onKeyPress($event)">
        <p> {{keyPressed}} </p>

    </section>
    <app-sidebar></app-sidebar>
</div>
<div class="clearfix"></div>

// AprendiendoVueJs/src/components/Formulario.vue
<template>
  <div class="general">
    <Slider title="Formulario" />
    <div class="center">
      <section class="content">
        <h2 class="subheader">Formulario</h2>

        <form class="mid-form" @submit.prevent="mostrarUsuario()">
          <div class="form-group">
            <label for="name">Nombre:</label>
            <input type="text" name="name" id="name" v-model="user.nombre" />
            <div v-if="submitted && !$v.user.nombre.required">Este campo es requerido</div>
            <div v-if="submitted && !$v.user.nombre.minLength">Este campo debe tener mas letras</div>
          </div>
          <div class="form-group">
            <label for="lastname">Apellido:</label>
            <input type="text" name="lastname" id="lastname" v-model="user.apellidos" />
            <div v-if="submitted && !$v.user.apellidos.required">Este campo es requerido</div>
            <div v-if="submitted && !$v.user.apellidos.minLength">Este campo debe tener mas letras</div>
          </div>
          <div class="form-group radio">
            <label for="name">Biografia:</label>
            <textarea name="bio" id cols="30" rows="10" v-model="user.bio"></textarea>
            <div v-if="submitted && !$v.user.bio.required">Este campo es requerido</div>
          </div>
          <div class="form-group radio">
            <input type="radio" name="genre" value="hombre" v-model="user.genero" /> Hombre
            <input type="radio" name="genre" value="mujer" v-model="user.genero" /> Mujer
            <input type="radio" name="genre" value="otro" v-model="user.genero" /> Otro
          </div>
          <div class="clearfix"></div>

          <input type="submit" value="Enviar" class="btn btn-success" />
        </form>

        <div class="datos" v-if="user && user.nombre && user.apellidos">
          <h3>{{user.nombre + ' ' + user.apellidos}}</h3>
        </div>
      </section>
      <Sidebar />
    </div>
    <div class="clearfix"></div>
  </div>
</template>

<script>
import Sidebar from "./Sidebar.vue";
import Slider from "./Slider.vue";
import { required, minLength } from "vuelidate/lib/validators";

export default {
  name: "Formulario",
  components: {
    Sidebar,
    Slider
  },
  validations: {
    user: {
      nombre: {
        required,
        minLength: minLength(2)
      },
      apellidos: {
        required,
        minLength: minLength(2)
      },
      bio: {
        required
      }
    }
  },
  data() {
    return {
      submitted: false,
      user: {
        nombre: null,
        apellidos: null,
        bio: null,
        genero: null
      }
    };
  },
  methods: {
    mostrarUsuario() {
      this.submitted = true;

      this.$v.$touch();
      if (this.$v.$invalid) {
        return false;
      }

      alert("enviar forms");
    }
  }
};
</script>

<style>
</style>
