// AprendiendoAngular/src/app/components/search/search.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router, Params } from '@angular/router';
import { ArticleService } from '../../services/article.service';
import { Article } from '../../models/article';


@Component({
    selector: 'app-search',
    templateUrl: './search.component.html',
    styleUrls: ['./search.component.css']
})
export class SearchComponent implements OnInit {
    public articles: Array<Article>;
    public token: string;

    constructor(
        private _route: ActivatedRoute,
        private _router: Router,
        private _article: ArticleService
    ) { }

    ngOnInit(): void {
        this._route.params.subscribe((params: Params) => {
            const token = params.token;
            this.token = token;
            this._article.search(token).subscribe(
                res => {
                    if (res.articles) {
                        this.articles = res.articles;
                    }
                },
                err => {
                    console.log(err);
                    if (err.status === 404) {
                        this.articles = [];
                    }
                    // this._router.navigate(['/home']);
                }
            );
        });
    }


}

<app-slider [name]="'Busqueda: '+token" [size]="'small'"></app-slider>

<div class="center">
    <section class="content">
        <h2 class="subheader">Articulos encontrados</h2>
        <app-articles [articles]="articles" *ngIf="articles"></app-articles>
    </section>
    <app-sidebar></app-sidebar>
</div>
<div class="clearfix"></div>

// AprendiendoVueJs/src/components/Search.vue
<template>
  <div class="general">
    <Slider :title="'Busqueda: '+searchToken" />
    <div class="center">
      <section class="content">
        <h2 class="subheader">Articulos encontrados</h2>
        <div id="articles" v-if="articles.length > 0">
          <Articles :articles="articles" />
        </div>
        <div v-else>
          <h2>No hay articulos que coincidan con tu busqueda</h2>
        </div>
      </section>
      <Sidebar />
    </div>
    <div class="clearfix"></div>
  </div>
</template>

<script>
import Sidebar from "./Sidebar.vue";
import Slider from "./Slider.vue";
import Articles from "./Articles.vue";
import Axios from "axios";
import Global from "../global";

export default {
  name: "Search",
  components: {
    Sidebar,
    Slider,
    Articles
  },
  mounted() {
    this.searchToken = this.$route.params.token;
    this.getArticlesBySearch(this.searchToken);
  },
  methods: {
    getArticlesBySearch(token) {
      Axios.get(Global.uri + "search/" + token)
        .then(res => {
          if (res.data.status === "ok") {
            this.articles = res.data.articles;
          }
          console.log(this.articles);
        })
        .catch(err => console.log(err.message));
    }
  },
  data() {
    return {
      searchToken: null,
      articles: []
    };
  }
};
</script>

<style>
</style>
