// AprendiendoAngular/src/app/components/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
    selector: 'app-sidebar',
    templateUrl: './sidebar.component.html',
    styleUrls: ['./sidebar.component.css']
})
export class SidebarComponent implements OnInit {
    public seachToken: string;

    constructor(
        private _route: ActivatedRoute,
        private _router: Router
    ) { }

    ngOnInit(): void {
    }

    goSearch() {

        this._router.navigate(['buscar', this.seachToken]);
    }

}

<aside class="sidebar">
    <div class="nav-blog sidebar-item">
        <h3>Puedes hacer esto</h3>
        <a [routerLink]="['/blog/crear']" class="btn btn-success">Crear articulo</a>
    </div>
    <div class="search sidebar-item">
        <h3>buscador</h3>
        <p>Busca lo que gustes</p>
        <form #searchForm="ngForm" (ngSubmit)="goSearch()">
            <input type="text" name="search" [(ngModel)]="seachToken">
            <input type="submit" value="Buscar" class="btn">
        </form>
    </div>
</aside>

// AprendiendoVueJs/src/components/Sidebar.vue
<template>
  <aside class="sidebar">
    <div class="nav-blog sidebar-item">
      <h3>Puedes hacer esto</h3>
      <a href="#" class="btn btn-success">Crear articulo</a>
    </div>
    <div class="search sidebar-item">
      <h3>buscador</h3>
      <p>Busca lo que gustes</p>
      <form>
        <input type="text" name="search" />
        <input type="submit" value="Buscar" class="btn" />
      </form>
    </div>
  </aside>
</template>

<script>
export default {
  name: "Sidebar"
};
</script>
