// AprendiendoVueJs/src/components/Article.vue
<template>
  <div class="general">
    <div class="center">
      <section class="content">
        <article class="article-item article-detail" id="article-item" v-if="article">
          <div class="image-wrap">
            <img v-if="article.image" :src="uri+'image/'+article.image" :alt="article.title" />
            <img v-if="!article.image" src="../assets/logo.png" :alt="article.title" />
          </div>
          <h1 class="subheader">{{article.title}}</h1>
          <span class="date">{{article.date | moment('from', 'now')}}</span>
          <p>{{article.content}}</p>

          <div class="clearfix"></div>
          <router-link :to="'/editar/'+article._id" class="btn btn-warning">Editar</router-link>
          <a @click="deleteArticle(article._id)" class="btn btn-danger">Eliminar</a>
        </article>
      </section>
      <Sidebar />
    </div>
    <div class="clearfix"></div>
  </div>
</template>

<script>
import Sidebar from "./Sidebar.vue";
import Global from "../global";
import Axios from "axios";
import swal from "sweetalert";

export default {
  name: "Article",
  components: {
    Sidebar
  },
  data() {
    return {
      uri: Global.uri,
      article: null
    };
  },
  mounted() {
    let id = this.$route.params.id;
    this.getArticle(id);
  },
  methods: {
    getArticle(id) {
      Axios.get(this.uri + "article/" + id)
        .then(res => {
          if (res.data.status === "ok") {
            this.article = res.data.article;
          }
        })
        .catch(err => console.log(err.message));
    },
    deleteArticle(id) {
      swal({
        title: `¿Estas seguro que deseas eliminar ${this.article.title}?`,
        text: "una vez eliminado, no podras recuperarlo",
        icon: "warning",
        buttons: true,
        dangerMode: true
      }).then(willDelete => {
        if (willDelete) {
          Axios.delete(this.uri + "article/" + id)
            .then(res => {
              if (res.data.status === "ok") {
                swal("Poof! Tu articulo ha sido eliminado!", {
                  icon: "success"
                });
              }
              this.$router.push("/blog");
            })
            .catch();
        } else {
          swal("Tu articulo esta a salvo!");
        }
      });
    }
  }
};
</script>

<style>
</style>

// AprendiendoAngular/src/app/components/article/article.component.ts
import { Component, OnInit } from '@angular/core';
import { ArticleService } from '../../services/article.service';
import { Article } from '../../models/article';
import { ActivatedRoute, Params, Router } from '@angular/router';
import { config } from 'src/app/services/config.service';
import swal from 'sweetalert';

@Component({
    selector: 'app-article',
    templateUrl: './article.component.html',
    styleUrls: ['./article.component.css']
})
export class ArticleComponent implements OnInit {

    public article: Article;

    constructor(
        private _article: ArticleService,
        private _route: ActivatedRoute,
        private _router: Router
    ) { }

    ngOnInit(): void {
        this._route.params.subscribe((params: Params) => {
            const id = params.id;

            this._article.getArticle(id).subscribe(
                res => {
                    if (res.article) {
                        this.article = res.article;
                    } else {
                        this._router.navigate(['/home']);
                    }

                }, err => {
                    console.log(err);
                });
        });


    }

    delete(id: string) {
        swal({
            title: '¿Estas seguro?',
            text: 'Una vez eliminado no lo podras recuperar',
            icon: 'warning',
            buttons: ['Cancelar', 'Eliminar'],
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {
                    this._article.delete(id).subscribe(
                        res => {
                            swal('El articulo ha sido eliminado', {
                                icon: 'success',
                            });
                            this._router.navigate(['/blog']);
                        },
                        err => {
                            this._router.navigate(['/blog']);
                            console.log(err);
                        }
                    );
                } else {
                    swal('Se ha cancelado este proceso.');
                }
            });


    }

    getImage(img: string) {
        return `${config.uri + 'image/' + img}`;
    }

}

<div class="center">
    <section class="content">
        <article class="article-item article-detail" id="article-item" *ngIf="article">

            <div class="image-wrap">
                <img *ngIf="article.image" src="{{getImage(article.image)}}" alt="{{article.title}}">
                <img *ngIf="!article.image" src="assets/images/default.jpg" alt="{{article.title}}">
            </div>
            <h1 class="subheader">{{article.title}}</h1>
            <span class="date">{{article.date | amLocale: 'es' | amTimeAgo}}</span>
            <p>
                {{article.content}}
            </p>
            <div class="buttons">

                <a [routerLink]="['/blog/editar', article._id]" class="btn btn-warning">Editar</a>
                <a (click)="delete(article._id)" class="btn btn-danger">Borrar</a>
            </div>

        </article>

    </section>
    <app-sidebar></app-sidebar>
</div>
<div class="clearfix"></div>
