// AprendiendoVueJs/src/components/Blog.vue
<template>
  <div class="general">
    <Slider title="Blog" />
    <div class="center">
      <section class="content">
        <h2 class="subheader">Blog</h2>
      </section>
      <Sidebar />
    </div>
    <div class="clearfix"></div>
  </div>
</template>

<script>
import Sidebar from "./Sidebar.vue";
import Slider from "./Slider.vue";

export default {
  name: "Blog",
  components: {
    Sidebar,
    Slider
  }
};
</script>

<style>
</style>

// AprendiendoAngular/src/app/components/blog/blog.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-blog',
    templateUrl: './blog.component.html',
    styleUrls: ['./blog.component.css']
})
export class BlogComponent implements OnInit {

    constructor() { }

    ngOnInit(): void {
    }

}

<app-slider [name]="'Blog'" [size]="'small'"></app-slider>

<div class="center">
    <section class="content">

    </section>
    <app-sidebar></app-sidebar>
</div>
<div class="clearfix"></div>
