// AprendiendoVueJs/src/components/Articles.vue
<template>
  <div id="list-articles">
    <article class="article-item" id="article-item" v-for="article in articles" :key="article._id">
      <div class="image-wrap">
        <img v-if="article.image" :src="uri+'image/'+article.image" :alt="article.title" />
        <img v-if="!article.image" src="../assets/logo.png" :alt="article.title" />
      </div>
      <h2>{{article.title}}</h2>
      <span class="date">{{article.date}}</span>
      <a href="#">Leer mas</a>
      <div class="clearfix"></div>
    </article>
  </div>
</template>

<script>
import Global from "../global";

export default {
  name: "Articles",
  props: ["articles"],
  data() {
    return {
      uri: Global.uri
    };
  }
};
</script>

<style>
</style>

// AprendiendoAngular/src/app/components/articles/articles.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Article } from '../../models/article';
import { config } from '../../services/config.service';

@Component({
    selector: 'app-articles',
    templateUrl: './articles.component.html',
    styleUrls: ['./articles.component.css']
})
export class ArticlesComponent implements OnInit {
    @Input() articles: Array<Article>;
    public uri: string;

    constructor() {
        this.uri = config.uri;
    }

    ngOnInit(): void {

    }

    getImage(img: string) {
        return `${config.uri + 'image/' + img}`;
    }
}

<div class="loading" *ngIf="!articles">
    Cargando...
</div>
<div *ngIf="articles">
    <article class="article-item " *ngFor="let article of articles">
        <div class="image-wrap">
            <img src="{{getImage(article.image)}}" alt="{{article.title}}" *ngIf="article.image">
            <img src="assets/images/default.jpg" alt="{{article.title}}" *ngIf="!article.image">
        </div>
        <h2>
            {{article.title}}
        </h2>
        <span class="date">
            {{article.date | amLocale: 'es' |amTimeAgo}}
        </span>
        <a [routerLink]="['/blog/articulo', article._id]">Leer mas</a>

        <div class="clearfix"></div>
    </article>
</div>
