// AprendiendoReact/src/components/Home.jsx
import React, { Component } from 'react'
import Slider from './Slider'
import Sidebar from './Sidebar'

export default class Home extends Component {
    render() {
        return (
            <div id="home">
                <Slider
                    titulo="Maquetacion de ReactJs del Master de Frameworks de Js"
                    btn="Ver mas"
                    size="slider-big"
                />
                <div className="center">
                    <div className="content">
                        <h1 className="subheader">Ultimos Articulos</h1>
                    </div>

                    <Sidebar></Sidebar>
                </div>
            </div>
        )
    }
}

// AprendiendoAngular/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-home',
    templateUrl: './home.component.html',
    styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
    public title: string;
    constructor() {
        this.title = 'Ultimos Articulos';
    }

    ngOnInit(): void {
    }

}

<app-slider [name]="'Maquetacion de Angular del Master de Frameworks de Js'"></app-slider>

<div class="center">
    <section class="content">
        <h2 class="subheader">{{title}}</h2>
        <app-articles [articles]="lastArticles"></app-articles>
    </section>
    <app-sidebar></app-sidebar>
</div>
<div class="clearfix"></div>
