// AprendiendoVueJs/src/components/Blog.vue
<template>
  <div class="general">
    <Slider title="Blog" />
    <div class="center">
      <section class="content">
        <h2 class="subheader">Blog</h2>
      </section>
      <Sidebar />
    </div>
    <div class="clearfix"></div>
  </div>
</template>

<script>
import Sidebar from "./Sidebar.vue";
import Slider from "./Slider.vue";

export default {
  name: "Blog",
  components: {
    Sidebar,
    Slider
  }
};
</script>

<style>
</style>

// AprendiendoReact/src/components/Blog.jsx
import React, { Component } from 'react'
import Slider from './Slider'
import Sidebar from './Sidebar'

export default class Blog extends Component {
    render() {
        return (
            <div id="blog">
                <Slider
                    titulo="Blog"
                    size="slider-small"></Slider>

                <div className="center">
                    <div className="content">
                        {/* listado de articulos de la api */}
                    </div>
                    <Sidebar
                        blog={true}
                    ></Sidebar>
                </div>
            </div>

        )
    }
}
