// AprendiendoVueJs/src/components/Header.vue
<template>
  <header class="header">
    <div class="center">
      <!-- logo -->
      <div class="logo">
        <img src="../assets/logo.png" alt="Logo de la web" class="app-logo" />
        <div class="brand">
          <strong>Curso</strong>Vue
        </div>
      </div>
      <!-- menu -->

      <nav class="menu">
        <ul>
          <li>
            <a href="index.html">Inicio</a>
          </li>
          <li>
            <a href="blog.html">Blog</a>
          </li>
          <li>
            <a href="form.html">Formulario</a>
          </li>
          <li>
            <a href="#">Pagina 1</a>
          </li>
          <li>
            <a href="#">Pagina 2</a>
          </li>
        </ul>
      </nav>
    </div>
    <!-- limpiar flotantes -->
    <div class="clearfix"></div>
  </header>
</template>

<script>
export default {
  name: "Header"
};
</script>

// AprendiendoReact/src/components/Header.jsx
import React, { Component } from 'react'
import Logo from '../assets/images/logo.svg';

export default class Header extends Component {
    render() {
        return (
            <header className="header">
                <div className="center">

                    <div className="logo">
                        <img src={Logo} alt="Logo de la web" className="app-logo" />
                        <div className="brand">
                            <strong>Curso</strong>ReactJS
                            </div>
                    </div>
                    <nav className="menu">
                        <ul>
                            <li>
                                <a href="index.html">Inicio</a>
                            </li>
                            <li>
                                <a href="blog.html">Blog</a>
                            </li>
                            <li>
                                <a href="form.html">Formulario</a>
                            </li>
                            <li>
                                <a href="dd">Pagina 1</a>
                            </li>
                            <li>
                                <a href="dd">Pagina 2</a>
                            </li>
                        </ul>
                    </nav>
                </div>

                <div className="clearfix"></div>
            </header>
        )
    }
}
