// AprendiendoVueJs/src/components/Pelicula.vue
<template>
  <article class="article-item">
    <div class="image-wrap">
      <img :src="pelicula.image" :alt="pelicula.title" />
    </div>
    <h2>{{pelicula.title}}</h2>
    <span
      class="date"
      :class="{
            'year-green': pelicula.year <= 2020,
            'year-red': pelicula.year > 2020
            }"
    >{{pelicula.year}}</span>
    <input type="button" value="Marcar como Favorito" @click="pasarFavoritaAlPadre(pelicula)" />
    <div class="clearfix"></div>
  </article>
</template>

<script>
export default {
  name: "Pelicula",
  props: ["pelicula"],
  methods: {
    pasarFavoritaAlPadre(pelicula) {
      //   console.log(pelicula);
      this.$emit("favorita", pelicula);
    }
  }
};
</script>

<style>
</style>

// AprendiendoReact/src/components/Pelicula.jsx
import React, { Component } from 'react'

export default class Pelicula extends Component {

    marcar = () => {
        this.props.marcarFavorita(this.props.pelicula, this.props.index);
    }

    render() {
        const { titulo, image } = this.props.pelicula
        return (
            <div id="pelicula">
                <article className="article-item" id="article-item">
                    <div className="image-wrap">
                        <img src={image} alt={titulo} />
                    </div>
                    <h2>{titulo}</h2>
                    <span className="date">Hace 5 minutos</span>
                    <a href="d">Leer mas</a>
                    <button
                        onClick={this.marcar}
                    >
                        Marcar como favorita
                    </button>
                    <div className="clearfix"></div>
                </article>
            </div>
        )
    }
}
