// AprendiendoVueJs/src/components/Slider.vue
<template>
  <div :class="{
      'slider slider-big': home,
      'slider slider-small': !home
  }">
    <h1>{{title}}</h1>
    <router-link to="/blog" class="btn-white" v-if="home">Ir al blog</router-link>
  </div>
</template>

<script>
export default {
  name: "Slider",
  props: ["title", "home"]
};
</script>

// AprendiendoReact/src/components/Slider.jsx
import React, { Component } from 'react'
import { Link } from 'react-router-dom'

export default class Slider extends Component {
    render() {
        return (
            <div className={'slider ' + this.props.size}>
                <h1>{this.props.titulo}</h1>
                {
                    this.props.btn &&
                    <Link to="/blog" className="btn-white">{this.props.btn}</Link>
                }
            </div>
        )
    }
}
